import re

with open('/Volumes/Coding/GloPro/src/lib/i18n.jsx', 'r', encoding='utf-8') as f:
    i18n_content = f.read()

new_translations = {
    'vi': """
    'customers.detail.title': 'Chi tiết khách hàng',
    'common.actions': 'Thao tác',
    'customers.detail.book_now': 'Đặt lịch ngay',
    'customers.detail.create_invoice': 'Tạo hóa đơn',
    'customers.detail.last_visit': 'Truy cập lần cuối:',
    'common.today': 'Hôm nay',
    'customers.detail.stats_appointments': 'Lịch hẹn',
    'customers.detail.stats_points': 'Tích điểm',
    'customers.detail.stats_spend': 'Chi tiêu (đ)',
    'customers.tabs.deposits': 'Đặt cọc',
    'customers.tabs.invoices': 'Hóa đơn',
    'customers.tabs.services': 'Dịch vụ',
    'customers.tabs.products': 'Sản phẩm',
    'customers.tabs.service_combos': 'Combo dịch vụ',
    'customers.tabs.product_combos': 'Combo sản phẩm',
    'customers.tabs.cash_cards': 'Thẻ tiền mặt',
    'customers.tabs.packages': 'Gói dịch vụ',
    'customers.tabs.treatments': 'Liệu trình',
    'customers.tabs.notes': 'Ghi chú',
    'customers.tabs.promotions': 'Khuyến mãi',
    'customers.tabs.messages': 'Tin nhắn',
    'customers.detail.appointments_list': 'Danh sách lịch hẹn',
    'customers.detail.search_appointments_placeholder': 'Tìm theo mã, KTV, dịch vụ...',
    'common.filter': 'Lọc',
    'customers.detail.booking_code': 'Mã lịch',
    'common.date_time': 'Ngày & giờ',
    'common.service': 'Dịch vụ',
    'common.status': 'Trạng thái',
    'common.total': 'Tổng tiền',
    'common.action': 'Hành động',
    'customers.purchases.services_bought': 'Dịch vụ đã mua',
    'customers.purchases.no_services': 'Chưa mua dịch vụ nào',
    'customers.purchases.products_bought': 'Sản phẩm đã mua',
    'customers.purchases.no_products': 'Chưa mua sản phẩm nào',
    'customers.purchases.service_combos_bought': 'Combo dịch vụ đã mua',
    'customers.purchases.no_service_combos': 'Chưa mua combo dịch vụ nào',
    'customers.purchases.product_combos_bought': 'Combo sản phẩm đã mua',
    'customers.purchases.no_product_combos': 'Chưa mua combo sản phẩm nào',
    'customers.detail.cash_cards_accumulated': 'Thẻ tiền mặt tích lũy',
    'customers.detail.prepaid_packages': 'Gói dịch vụ combo trả trước',
    'customers.detail.promotions_gifts': 'Khuyến mãi & Quà tặng của khách',
    'customers.detail.give_promotion': 'Tặng Khuyến mãi',
    'customers.detail.internal_notes': 'Ghi chú nội bộ',
    'customers.detail.booking_code_colon': 'Mã lịch hẹn:',
    'common.service_colon': 'Dịch vụ:',
    'common.status_colon': 'Trạng thái:',
    'common.total_colon': 'Tổng tiền:',
    'customers.detail.card_actions': 'Thao tác thẻ',
    'customers.detail.expected_appointments': 'Danh sách lịch hẹn dự kiến',
    'common.unassigned': 'Chưa phân',
    'customers.detail.package_completed': 'Gói dịch vụ đã hoàn thành',
    'customers.detail.treatment_completed': 'Liệu trình đã hoàn thành',
    'common.staff': 'Nhân viên',
    """,
    'en': """
    'customers.detail.title': 'Customer Details',
    'common.actions': 'Actions',
    'customers.detail.book_now': 'Book Now',
    'customers.detail.create_invoice': 'Create Invoice',
    'customers.detail.last_visit': 'Last Visit:',
    'common.today': 'Today',
    'customers.detail.stats_appointments': 'Appointments',
    'customers.detail.stats_points': 'Points',
    'customers.detail.stats_spend': 'Spend (VND)',
    'customers.tabs.deposits': 'Deposits',
    'customers.tabs.invoices': 'Invoices',
    'customers.tabs.services': 'Services',
    'customers.tabs.products': 'Products',
    'customers.tabs.service_combos': 'Service Combos',
    'customers.tabs.product_combos': 'Product Combos',
    'customers.tabs.cash_cards': 'Cash Cards',
    'customers.tabs.packages': 'Packages',
    'customers.tabs.treatments': 'Treatments',
    'customers.tabs.notes': 'Notes',
    'customers.tabs.promotions': 'Promotions',
    'customers.tabs.messages': 'Messages',
    'customers.detail.appointments_list': 'Appointments List',
    'customers.detail.search_appointments_placeholder': 'Search by code, staff, service...',
    'common.filter': 'Filter',
    'customers.detail.booking_code': 'Booking Code',
    'common.date_time': 'Date & Time',
    'common.service': 'Service',
    'common.status': 'Status',
    'common.total': 'Total',
    'common.action': 'Action',
    'customers.purchases.services_bought': 'Purchased Services',
    'customers.purchases.no_services': 'No purchased services',
    'customers.purchases.products_bought': 'Purchased Products',
    'customers.purchases.no_products': 'No purchased products',
    'customers.purchases.service_combos_bought': 'Purchased Service Combos',
    'customers.purchases.no_service_combos': 'No purchased service combos',
    'customers.purchases.product_combos_bought': 'Purchased Product Combos',
    'customers.purchases.no_product_combos': 'No purchased product combos',
    'customers.detail.cash_cards_accumulated': 'Accumulated Cash Cards',
    'customers.detail.prepaid_packages': 'Prepaid Combo Packages',
    'customers.detail.promotions_gifts': 'Customer Promotions & Gifts',
    'customers.detail.give_promotion': 'Give Promotion',
    'customers.detail.internal_notes': 'Internal Notes',
    'customers.detail.booking_code_colon': 'Booking Code:',
    'common.service_colon': 'Service:',
    'common.status_colon': 'Status:',
    'common.total_colon': 'Total:',
    'customers.detail.card_actions': 'Card Actions',
    'customers.detail.expected_appointments': 'Expected Appointments',
    'common.unassigned': 'Unassigned',
    'customers.detail.package_completed': 'Package Completed',
    'customers.detail.treatment_completed': 'Treatment Completed',
    'common.staff': 'Staff',
    """,
    'ko': """
    'customers.detail.title': '고객 상세',
    'common.actions': '작업',
    'customers.detail.book_now': '지금 예약',
    'customers.detail.create_invoice': '송장 작성',
    'customers.detail.last_visit': '최근 방문:',
    'common.today': '오늘',
    'customers.detail.stats_appointments': '예약',
    'customers.detail.stats_points': '포인트',
    'customers.detail.stats_spend': '지출 (VND)',
    'customers.tabs.deposits': '예치금',
    'customers.tabs.invoices': '송장',
    'customers.tabs.services': '서비스',
    'customers.tabs.products': '제품',
    'customers.tabs.service_combos': '서비스 콤보',
    'customers.tabs.product_combos': '제품 콤보',
    'customers.tabs.cash_cards': '현금 카드',
    'customers.tabs.packages': '패키지',
    'customers.tabs.treatments': '시술',
    'customers.tabs.notes': '메모',
    'customers.tabs.promotions': '프로모션',
    'customers.tabs.messages': '메시지',
    'customers.detail.appointments_list': '예약 목록',
    'customers.detail.search_appointments_placeholder': '코드, 직원, 서비스로 검색...',
    'common.filter': '필터',
    'customers.detail.booking_code': '예약 코드',
    'common.date_time': '날짜 및 시간',
    'common.service': '서비스',
    'common.status': '상태',
    'common.total': '총액',
    'common.action': '작업',
    'customers.purchases.services_bought': '구매한 서비스',
    'customers.purchases.no_services': '구매한 서비스 없음',
    'customers.purchases.products_bought': '구매한 제품',
    'customers.purchases.no_products': '구매한 제품 없음',
    'customers.purchases.service_combos_bought': '구매한 서비스 콤보',
    'customers.purchases.no_service_combos': '구매한 서비스 콤보 없음',
    'customers.purchases.product_combos_bought': '구매한 제품 콤보',
    'customers.purchases.no_product_combos': '구매한 제품 콤보 없음',
    'customers.detail.cash_cards_accumulated': '누적 현금 카드',
    'customers.detail.prepaid_packages': '선불 콤보 패키지',
    'customers.detail.promotions_gifts': '고객 프로모션 및 선물',
    'customers.detail.give_promotion': '프로모션 증정',
    'customers.detail.internal_notes': '내부 메모',
    'customers.detail.booking_code_colon': '예약 코드:',
    'common.service_colon': '서비스:',
    'common.status_colon': '상태:',
    'common.total_colon': '총액:',
    'customers.detail.card_actions': '카드 작업',
    'customers.detail.expected_appointments': '예정된 예약',
    'common.unassigned': '미배정',
    'customers.detail.package_completed': '패키지 완료',
    'customers.detail.treatment_completed': '시술 완료',
    'common.staff': '직원',
    """,
    'ja': """
    'customers.detail.title': '顧客の詳細',
    'common.actions': 'アクション',
    'customers.detail.book_now': '今すぐ予約',
    'customers.detail.create_invoice': '請求書を作成',
    'customers.detail.last_visit': '最終来店:',
    'common.today': '今日',
    'customers.detail.stats_appointments': '予約',
    'customers.detail.stats_points': 'ポイント',
    'customers.detail.stats_spend': '利用額 (VND)',
    'customers.tabs.deposits': '預り金',
    'customers.tabs.invoices': '請求書',
    'customers.tabs.services': 'サービス',
    'customers.tabs.products': '商品',
    'customers.tabs.service_combos': 'サービスコンボ',
    'customers.tabs.product_combos': '商品コンボ',
    'customers.tabs.cash_cards': '現金カード',
    'customers.tabs.packages': 'パッケージ',
    'customers.tabs.treatments': 'トリートメント',
    'customers.tabs.notes': 'メモ',
    'customers.tabs.promotions': 'プロモーション',
    'customers.tabs.messages': 'メッセージ',
    'customers.detail.appointments_list': '予約リスト',
    'customers.detail.search_appointments_placeholder': 'コード、スタッフ、サービスで検索...',
    'common.filter': 'フィルター',
    'customers.detail.booking_code': '予約コード',
    'common.date_time': '日時',
    'common.service': 'サービス',
    'common.status': 'ステータス',
    'common.total': '合計',
    'common.action': 'アクション',
    'customers.purchases.services_bought': '購入したサービス',
    'customers.purchases.no_services': '購入したサービスはありません',
    'customers.purchases.products_bought': '購入した商品',
    'customers.purchases.no_products': '購入した商品はありません',
    'customers.purchases.service_combos_bought': '購入したサービスコンボ',
    'customers.purchases.no_service_combos': '購入したサービスコンボはありません',
    'customers.purchases.product_combos_bought': '購入した商品コンボ',
    'customers.purchases.no_product_combos': '購入した商品コンボはありません',
    'customers.detail.cash_cards_accumulated': '累積現金カード',
    'customers.detail.prepaid_packages': '前払いパッケージ',
    'customers.detail.promotions_gifts': '顧客プロモーションとギフト',
    'customers.detail.give_promotion': 'プロモーションを付与',
    'customers.detail.internal_notes': '内部メモ',
    'customers.detail.booking_code_colon': '予約コード:',
    'common.service_colon': 'サービス:',
    'common.status_colon': 'ステータス:',
    'common.total_colon': '合計:',
    'customers.detail.card_actions': 'カードアクション',
    'customers.detail.expected_appointments': '予定された予約',
    'common.unassigned': '未割り当て',
    'customers.detail.package_completed': 'パッケージ完了',
    'customers.detail.treatment_completed': 'トリートメント完了',
    'common.staff': 'スタッフ',
    """,
    'zh': """
    'customers.detail.title': '客户详情',
    'common.actions': '操作',
    'customers.detail.book_now': '立即预约',
    'customers.detail.create_invoice': '创建发票',
    'customers.detail.last_visit': '最后访问:',
    'common.today': '今天',
    'customers.detail.stats_appointments': '预约',
    'customers.detail.stats_points': '积分',
    'customers.detail.stats_spend': '消费 (VND)',
    'customers.tabs.deposits': '押金',
    'customers.tabs.invoices': '发票',
    'customers.tabs.services': '服务',
    'customers.tabs.products': '产品',
    'customers.tabs.service_combos': '服务套餐',
    'customers.tabs.product_combos': '产品套餐',
    'customers.tabs.cash_cards': '现金卡',
    'customers.tabs.packages': '套餐',
    'customers.tabs.treatments': '疗程',
    'customers.tabs.notes': '备注',
    'customers.tabs.promotions': '促销',
    'customers.tabs.messages': '消息',
    'customers.detail.appointments_list': '预约列表',
    'customers.detail.search_appointments_placeholder': '按代码、员工、服务搜索...',
    'common.filter': '过滤',
    'customers.detail.booking_code': '预约代码',
    'common.date_time': '日期与时间',
    'common.service': '服务',
    'common.status': '状态',
    'common.total': '总计',
    'common.action': '操作',
    'customers.purchases.services_bought': '已购服务',
    'customers.purchases.no_services': '无已购服务',
    'customers.purchases.products_bought': '已购产品',
    'customers.purchases.no_products': '无已购产品',
    'customers.purchases.service_combos_bought': '已购服务套餐',
    'customers.purchases.no_service_combos': '无已购服务套餐',
    'customers.purchases.product_combos_bought': '已购产品套餐',
    'customers.purchases.no_product_combos': '无已购产品套餐',
    'customers.detail.cash_cards_accumulated': '累积现金卡',
    'customers.detail.prepaid_packages': '预付套餐',
    'customers.detail.promotions_gifts': '客户促销与礼物',
    'customers.detail.give_promotion': '赠送促销',
    'customers.detail.internal_notes': '内部备注',
    'customers.detail.booking_code_colon': '预约代码:',
    'common.service_colon': '服务:',
    'common.status_colon': '状态:',
    'common.total_colon': '总计:',
    'customers.detail.card_actions': '卡操作',
    'customers.detail.expected_appointments': '预期预约',
    'common.unassigned': '未分配',
    'customers.detail.package_completed': '套餐已完成',
    'customers.detail.treatment_completed': '疗程已完成',
    'common.staff': '员工',
    """
}

for lang in ['vi', 'en', 'ko', 'ja', 'zh']:
    marker = f"{lang}: {{"
    replacement = f"{marker}\n{new_translations[lang]}"
    i18n_content = i18n_content.replace(marker, replacement)

with open('/Volumes/Coding/GloPro/src/lib/i18n.jsx', 'w', encoding='utf-8') as f:
    f.write(i18n_content)

print("i18n.jsx modified with customer detail strings.")
