import re

with open('/Volumes/Coding/GloPro/src/lib/i18n.jsx', 'r', encoding='utf-8') as f:
    i18n_content = f.read()

new_translations = {
    'vi': """
    'customers.detail.invoice_payment_history': 'Lịch sử thanh toán hóa đơn',
    'customers.detail.deposit_history': 'Lịch sử đặt cọc',
    'customers.detail.no_deposit_history': 'Chưa có lịch sử đặt cọc nào.',
    'customers.detail.deposit_code': 'Mã ĐC',
    'common.created_date': 'Ngày tạo',
    'customers.detail.required_deposit': 'Cần cọc',
    'customers.detail.paid_deposit': 'Đã cọc',
    'common.status_collected': 'Đã thu',
    'common.status_partially_collected': 'Thu một phần',
    'common.status_applied': 'Đã áp dụng',
    'common.status_refunded': 'Đã hoàn',
    'customers.detail.activity_timeline': 'Dòng thời gian hoạt động',
    'customers.detail.register_profile': 'Đăng ký hồ sơ khách hàng',
    'customers.detail.create_new_profile_desc': 'Khởi tạo hồ sơ khách hàng mới trên hệ thống GloPro.',
    'customers.detail.update_tier': 'Cập nhật hạng thành viên:',
    'common.reason': 'Lý do:',
    'customers.detail.no_promotions': 'Không có chương trình khuyến mãi nào đang bật tính năng Quà tặng.',
    'common.status_unused': 'Chưa dùng',
    'customers.detail.message_history': 'Lịch sử tin nhắn đã gửi cho khách hàng',
    'customers.detail.add_new_note': 'Thêm ghi chú mới',
    'customers.detail.no_internal_notes': 'Chưa có ghi chú nội bộ cho khách hàng này',
    'customers.detail.card_and_usage_history': 'Thẻ & Lịch sử tiêu dùng',
    'customers.detail.transaction_history': 'Lịch sử giao dịch',
    'common.lifetime': 'Vô thời hạn',
    'common.expired_colon': 'Hết hạn:',
    'customers.detail.card_balance': 'Số dư thẻ',
    'customers.detail.usage_limit': 'Hạn mức sử dụng',
    'customers.detail.sessions_count': 'Số buổi',
    'common.purchase_date': 'Ngày mua',
    'customers.detail.used': 'Đã dùng',
    'customers.detail.sessions': 'buổi',
    """,
    'en': """
    'customers.detail.invoice_payment_history': 'Invoice Payment History',
    'customers.detail.deposit_history': 'Deposit History',
    'customers.detail.no_deposit_history': 'No deposit history.',
    'customers.detail.deposit_code': 'Deposit Code',
    'common.created_date': 'Created Date',
    'customers.detail.required_deposit': 'Required Deposit',
    'customers.detail.paid_deposit': 'Paid Deposit',
    'common.status_collected': 'Collected',
    'common.status_partially_collected': 'Partially Collected',
    'common.status_applied': 'Applied',
    'common.status_refunded': 'Refunded',
    'customers.detail.activity_timeline': 'Activity Timeline',
    'customers.detail.register_profile': 'Register Profile',
    'customers.detail.create_new_profile_desc': 'Created new customer profile on GloPro system.',
    'customers.detail.update_tier': 'Update Member Tier:',
    'common.reason': 'Reason:',
    'customers.detail.no_promotions': 'No promotions are currently enabling Gift features.',
    'common.status_unused': 'Unused',
    'customers.detail.message_history': 'Message History Sent to Customer',
    'customers.detail.add_new_note': 'Add New Note',
    'customers.detail.no_internal_notes': 'No internal notes for this customer',
    'customers.detail.card_and_usage_history': 'Cards & Usage History',
    'customers.detail.transaction_history': 'Transaction History',
    'common.lifetime': 'Lifetime',
    'common.expired_colon': 'Expired:',
    'customers.detail.card_balance': 'Card Balance',
    'customers.detail.usage_limit': 'Usage Limit',
    'customers.detail.sessions_count': 'Sessions',
    'common.purchase_date': 'Purchase Date',
    'customers.detail.used': 'Used',
    'customers.detail.sessions': 'sessions',
    """,
    'ko': """
    'customers.detail.invoice_payment_history': '송장 결제 내역',
    'customers.detail.deposit_history': '예치금 내역',
    'customers.detail.no_deposit_history': '예치금 내역이 없습니다.',
    'customers.detail.deposit_code': '예치금 코드',
    'common.created_date': '생성일',
    'customers.detail.required_deposit': '필요 예치금',
    'customers.detail.paid_deposit': '지불된 예치금',
    'common.status_collected': '수금됨',
    'common.status_partially_collected': '일부 수금됨',
    'common.status_applied': '적용됨',
    'common.status_refunded': '환불됨',
    'customers.detail.activity_timeline': '활동 타임라인',
    'customers.detail.register_profile': '프로필 등록',
    'customers.detail.create_new_profile_desc': 'GloPro 시스템에 새 고객 프로필이 생성되었습니다.',
    'customers.detail.update_tier': '멤버십 등급 업데이트:',
    'common.reason': '이유:',
    'customers.detail.no_promotions': '현재 선물 기능이 활성화된 프로모션이 없습니다.',
    'common.status_unused': '사용 안 함',
    'customers.detail.message_history': '고객에게 전송된 메시지 내역',
    'customers.detail.add_new_note': '새 메모 추가',
    'customers.detail.no_internal_notes': '이 고객에 대한 내부 메모가 없습니다',
    'customers.detail.card_and_usage_history': '카드 및 사용 내역',
    'customers.detail.transaction_history': '거래 내역',
    'common.lifetime': '평생',
    'common.expired_colon': '만료됨:',
    'customers.detail.card_balance': '카드 잔액',
    'customers.detail.usage_limit': '사용 한도',
    'customers.detail.sessions_count': '세션',
    'common.purchase_date': '구매일',
    'customers.detail.used': '사용됨',
    'customers.detail.sessions': '세션',
    """,
    'ja': """
    'customers.detail.invoice_payment_history': '請求書支払い履歴',
    'customers.detail.deposit_history': 'デポジット履歴',
    'customers.detail.no_deposit_history': 'デポジット履歴はありません。',
    'customers.detail.deposit_code': 'デポジットコード',
    'common.created_date': '作成日',
    'customers.detail.required_deposit': '必要なデポジット',
    'customers.detail.paid_deposit': '支払い済みデポジット',
    'common.status_collected': '回収済',
    'common.status_partially_collected': '一部回収済',
    'common.status_applied': '適用済',
    'common.status_refunded': '返金済',
    'customers.detail.activity_timeline': 'アクティビティタイムライン',
    'customers.detail.register_profile': 'プロファイル登録',
    'customers.detail.create_new_profile_desc': 'GloProシステムで新しい顧客プロファイルが作成されました。',
    'customers.detail.update_tier': 'メンバーシップランク更新:',
    'common.reason': '理由:',
    'customers.detail.no_promotions': '現在、ギフト機能が有効になっているプロモーションはありません。',
    'common.status_unused': '未使用',
    'customers.detail.message_history': '顧客へ送信したメッセージ履歴',
    'customers.detail.add_new_note': '新しいメモを追加',
    'customers.detail.no_internal_notes': 'この顧客の内部メモはありません',
    'customers.detail.card_and_usage_history': 'カードと利用履歴',
    'customers.detail.transaction_history': '取引履歴',
    'common.lifetime': '無期限',
    'common.expired_colon': '期限切れ:',
    'customers.detail.card_balance': 'カード残高',
    'customers.detail.usage_limit': '利用限度額',
    'customers.detail.sessions_count': 'セッション数',
    'common.purchase_date': '購入日',
    'customers.detail.used': '使用済',
    'customers.detail.sessions': 'セッション',
    """,
    'zh': """
    'customers.detail.invoice_payment_history': '发票支付记录',
    'customers.detail.deposit_history': '押金记录',
    'customers.detail.no_deposit_history': '暂无押金记录。',
    'customers.detail.deposit_code': '押金代码',
    'common.created_date': '创建日期',
    'customers.detail.required_deposit': '需要押金',
    'customers.detail.paid_deposit': '已付押金',
    'common.status_collected': '已收款',
    'common.status_partially_collected': '部分收款',
    'common.status_applied': '已应用',
    'common.status_refunded': '已退款',
    'customers.detail.activity_timeline': '活动时间线',
    'customers.detail.register_profile': '注册档案',
    'customers.detail.create_new_profile_desc': '在GloPro系统中创建了新的客户档案。',
    'customers.detail.update_tier': '更新会员等级:',
    'common.reason': '原因:',
    'customers.detail.no_promotions': '当前没有启用礼物功能的促销活动。',
    'common.status_unused': '未使用',
    'customers.detail.message_history': '发送给客户的消息记录',
    'customers.detail.add_new_note': '添加新备注',
    'customers.detail.no_internal_notes': '暂无该客户的内部备注',
    'customers.detail.card_and_usage_history': '卡与使用记录',
    'customers.detail.transaction_history': '交易记录',
    'common.lifetime': '无期限',
    'common.expired_colon': '已过期:',
    'customers.detail.card_balance': '卡余额',
    'customers.detail.usage_limit': '使用限额',
    'customers.detail.sessions_count': '次数',
    'common.purchase_date': '购买日期',
    'customers.detail.used': '已用',
    'customers.detail.sessions': '次',
    """
}

for lang in ['vi', 'en', 'ko', 'ja', 'zh']:
    marker = f"{lang}: {{"
    replacement = f"{marker}\n{new_translations[lang]}"
    i18n_content = i18n_content.replace(marker, replacement)

with open('/Volumes/Coding/GloPro/src/lib/i18n.jsx', 'w', encoding='utf-8') as f:
    f.write(i18n_content)

print("i18n.jsx modified with more customer detail strings.")
