/**
 * Permission Gate for AI Read Tools
 * 
 * Enforces application authorization based on authenticated user session / profile.
 * Never trusts permission claims generated by Gemini.
 */

import { ToolContext } from './contracts/ToolContracts';

export interface PermissionCheckResult {
  allowed: boolean;
  reason?: string;
  message?: string;
}

export class PermissionGate {
  /**
   * Evaluates whether the user has permission to execute the specified tool.
   */
  static check(toolName: string, requiredPermission: string | undefined, context: ToolContext): PermissionCheckResult {
    // If no permission required, allow
    if (!requiredPermission) {
      return { allowed: true };
    }

    const role = (context.role || '').toLowerCase();
    const permissions = context.permissions;

    // 1. Owner always has full access
    if (role === 'owner' || permissions === 'all') {
      return { allowed: true };
    }

    // 2. Blacklist check (from getCachedPermissions / RolePermission)
    if (permissions && typeof permissions === 'object' && 'type' in permissions && permissions.type === 'blacklist') {
      const blocked = permissions.blocked || [];
      if (blocked.includes(requiredPermission)) {
        return {
          allowed: false,
          reason: 'PERMISSION_DENIED',
          message: `🔒 Tài khoản của bạn (${role || 'nhân viên'}) không có quyền xem thông tin phân hệ "${requiredPermission}". Vui lòng liên hệ Quản lý hoặc Chủ salon.`
        };
      }
      return { allowed: true };
    }

    // 3. Array of explicit allowed permissions
    if (Array.isArray(permissions)) {
      if (permissions.includes('*') || permissions.includes(requiredPermission)) {
        return { allowed: true };
      }
      return {
        allowed: false,
        reason: 'PERMISSION_DENIED',
        message: `🔒 Bạn không có quyền truy cập dữ liệu thuộc phân hệ "${requiredPermission}".`
      };
    }

    // 4. Default role-based heuristic if permission structure is not loaded
    if (role === 'manager' || role === 'admin') {
      return { allowed: true };
    }

    if (role === 'technician' || role === 'staff') {
      // Technicians cannot view overall salon financial reports / revenue
      if (requiredPermission === 'reports' || requiredPermission === 'finance' || requiredPermission === 'revenue') {
        return {
          allowed: false,
          reason: 'PERMISSION_DENIED',
          message: `🔒 Thợ / Nhân viên không có quyền xem báo cáo doanh thu toàn salon.`
        };
      }
    }

    return { allowed: true };
  }
}
